"""Pydantic models for Stage 2 narration events."""

import time
from enum import Enum

from pydantic import BaseModel, Field

from voice_copilot.events.types import EventType


class NarrationPriority(str, Enum):
    """Priority level for a narration event.

    Determines how urgently the narration should be spoken:
      - CRITICAL: must be spoken immediately (e.g. agent blocked).
      - NORMAL: spoken in order when the TTS queue is free.
      - LOW: may be dropped if the queue is congested.
    """

    CRITICAL = "critical"
    NORMAL = "normal"
    LOW = "low"


class SummarizationMethod(str, Enum):
    """How the narration text was produced from the source event.

      - TEMPLATE: filled a static template string with event data.
      - LLM: generated by a language-model summarization call.
      - TRUNCATION: raw text was truncated to fit the TTS budget.
    """

    TEMPLATE = "template"
    LLM = "llm"
    TRUNCATION = "truncation"


class NarrationEvent(BaseModel):
    """A single narration payload ready for the TTS pipeline.

    Produced by Stage 2 (Filter & Summarize) from a raw
    ``VoiceCopilotEvent``.  Each ``NarrationEvent`` carries the final
    narration text, the priority that governs TTS scheduling, and
    traceability fields linking back to the originating event.
    """

    text: str
    priority: NarrationPriority
    source_event_type: EventType
    summarization_method: SummarizationMethod
    session_id: str
    timestamp: float = Field(default_factory=time.time)
    source_event_id: str | None = None
